/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    docs: [
    {
        type: 'autogenerated',
        dirName: '.'
    },
       
    {
        type: 'link',
        label: '联系我们', // 链接标签
        href: '/docs/helpdesk#contact', // 内部路径
    }

    ]

};

module.exports = sidebars;