name: Docs Build and Upload to Azure

on: 
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: 
      - 'docs/**'
      - 'versioned_docs/**'
      - 'i18n/**'
      - 'src/**'
      - 'static/**'
      - '**.js'
      - '!docs/_list'

jobs:
  build:
    runs-on: ubuntu-latest
    #if: false # stop steps
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v4
      with:
        node-version: 20        
    - name: Docusaurus build
      run: |
        yarn install
        yarn run build
      env:
        CI: true
    
      run: ls

    - name: Publish to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: eb79f13320db531d8cf1f3720966b695
        projectName: Documentation
        directory: build
        # Optional: Enable this if you want to have GitHub Deployments triggered
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        # Optional: Switch what branch you are publishing to.
        # By default this will be the branch which triggered this workflow
        branch: main