# 从制品文件生成 App 应用目录列表 Markdown。
# 触发方式：手动触发 或 repository_dispatch（事件名: applist_dev_event）。
# repository_dispatch 由 Websoft9 主仓库 release 时自动触发。

name: Sync App Catalog

on:
  workflow_dispatch:
  repository_dispatch:
    types: [applist_dev_event]

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: 'pip'

      - name: Install unzip utility
        run: sudo apt-get install unzip

      - name: Download and unzip JSON files
        run: |
          curl -L --retry 3 --retry-delay 5 --retry-connrefused --fail \
            -o media-latest.zip https://artifact.websoft9.com/release/websoft9/plugin/media/media-latest.zip
          unzip media-latest.zip "media/json/product_zh.json" "media/json/product_en.json" "media/json/catalog_zh.json" "media/json/catalog_en.json" -d ./extracted

      - name: Generate all Markdown files
        run: |
          # zh
          python builds/gen_app_index.py --json_file ./extracted/media/json/product_zh.json --output_file versioned_docs/version-2.0/apps/README.mdx --ignore-list template/meta/skip_applink.json
          python builds/gen_allcatalogs.py --json_file ./extracted/media/json/catalog_zh.json --output_file versioned_docs/version-2.0/apps/_include/allcatalogs.md
          python builds/gen_allapps.py --json_file ./extracted/media/json/product_zh.json --output_file versioned_docs/version-2.0/apps/_include/allapps.md
          # en
          python builds/gen_app_index.py --json_file ./extracted/media/json/product_en.json --output_file i18n/en/docusaurus-plugin-content-docs/version-2.0/apps/README.mdx --ignore-list template/meta/skip_applink.json
          python builds/gen_allcatalogs.py --json_file ./extracted/media/json/catalog_en.json --output_file i18n/en/docusaurus-plugin-content-docs/version-2.0/apps/_include/allcatalogs.md
          python builds/gen_allapps.py --json_file ./extracted/media/json/product_en.json --output_file i18n/en/docusaurus-plugin-content-docs/version-2.0/apps/_include/allapps.md

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Product Catalog Markdown
